// Generated by 'unplugin-auto-import'
export {}
declare global {
  const Message: typeof import('@arco-design/web-vue')['Message']
}
// for vue template auto import
import { UnwrapRef } from 'vue'
declare module 'vue' {
  interface ComponentCustomProperties {
    readonly Message: UnwrapRef<typeof import('@arco-design/web-vue')['Message']>
  }
}
